'''
Deep dive into parent_contribution calculation in dfs2
'''

def explain_parent_contribution():
    print("=" * 80)
    print("UNDERSTANDING parent_contribution in dfs2")
    print("=" * 80)
    
    print("\nThe KEY to rerooting: parent_contribution")
    print()
    print("When we move root from PARENT to CHILD:")
    print("  • CHILD becomes the new root")
    print("  • PARENT becomes just another subtree under CHILD")
    print("  • We need to calculate: what does PARENT contribute to CHILD?")
    print()
    
    print("=" * 80)
    print("EXAMPLE: Tree with more branches")
    print("=" * 80)
    print()
    print("        1")
    print("      / | \\")
    print("     2  3  4")
    print("    /")
    print("   5")
    print()
    
    print("When root=1:")
    print("  dp1[5] = 2  (leaf)")
    print("  dp1[2] = 3  (has child 5: 1 + 2)")
    print("  dp1[3] = 2  (leaf)")
    print("  dp1[4] = 2  (leaf)")
    print("  dp1[1] = 13 (has children 2,3,4: 1 + 3*2*2)")
    print()
    print("  Answer[1] = dp1[1] - 1 = 12")
    print()
    
    print("=" * 80)
    print("REROOTING from 1 → 2")
    print("=" * 80)
    print()
    print("Original view (root=1):")
    print("        1")
    print("      / | \\")
    print("     2  3  4      ← Node 1 has 3 children: 2, 3, 4")
    print("    /")
    print("   5")
    print()
    
    print("New view (root=2):")
    print("        2")
    print("       / \\")
    print("      5   1       ← Node 2 has 2 children: 5, and (1 with its subtree)")
    print("         / \\")
    print("        3   4")
    print()
    
    print("Calculating parent_contribution:")
    print("─────────────────────────────────")
    print()
    print("Q: When 2 becomes root, what does 1 contribute?")
    print()
    print("A: Node 1 now looks like a subtree from 2's perspective")
    print()
    print("   Step 1: Remove child 2's contribution from node 1")
    print("           remaining = parent_contrib * other_children")
    print("           remaining = 1 * dp1[3] * dp1[4]")
    print("           remaining = 1 * 2 * 2 = 4")
    print()
    print("   Step 2: Add 1 (for node 1 itself)")
    print("           node_contribution = 1 + remaining")
    print("           node_contribution = 1 + 4 = 5")
    print()
    print("   So when 2 is root:")
    print("     Answer[2] = dp1[5] * node_contribution")
    print("               = 2 * 5 = 10")
    print()
    
    print("=" * 80)
    print("REROOTING from 1 → 3")
    print("=" * 80)
    print()
    print("New view (root=3):")
    print("        3")
    print("        |")
    print("        1")
    print("       / \\")
    print("      2   4")
    print("     /")
    print("    5")
    print()
    
    print("Calculating parent_contribution:")
    print("─────────────────────────────────")
    print()
    print("Q: When 3 becomes root, what does 1 contribute?")
    print()
    print("   Step 1: Remove child 3's contribution from node 1")
    print("           remaining = 1 * dp1[2] * dp1[4]")
    print("           remaining = 1 * 3 * 2 = 6")
    print()
    print("   Step 2: Add 1")
    print("           node_contribution = 1 + 6 = 7")
    print()
    print("   So when 3 is root:")
    print("     Answer[3] = node_contribution")
    print("               = 7")
    print()
    
    print("=" * 80)
    print("THE FORMULA")
    print("=" * 80)
    print()
    print("When rerooting from PARENT to CHILD:")
    print()
    print("  parent_contribution = 1 + (parent's_parent_contrib * other_children)")
    print()
    print("  where other_children = all of parent's children EXCEPT the current child")
    print()
    print("This captures:")
    print("  • The parent node itself (+1)")
    print("  • All subtrees hanging off parent except the child we're moving to")
    print()
    
    print("=" * 80)
    print("CODE WALKTHROUGH")
    print("=" * 80)
    print()
    print("def dfs2(node, parent, parent_contribution):")
    print("    # 1. Calculate answer for current node")
    print("    prod = parent_contribution")
    print("    for child in adj[node]:")
    print("        if child != parent:")
    print("            prod *= dp1[child]  # Add all children")
    print("    ans[node] = prod")
    print()
    print("    # 2. Reroot to each child")
    print("    for child in adj[node]:")
    print("        if child != parent:")
    print("            # Calculate what THIS node contributes when child is root")
    print("            remaining = parent_contribution")
    print("            for other_child in adj[node]:")
    print("                if other_child != parent and other_child != child:")
    print("                    remaining *= dp1[other_child]")
    print()
    print("            node_contribution = 1 + remaining")
    print("            dfs2(child, node, node_contribution)")
    print()
    
    print("=" * 80)
    print("KEY INSIGHT")
    print("=" * 80)
    print()
    print("The magic of rerooting:")
    print()
    print("  Instead of recomputing EVERYTHING for each root (O(N²)),")
    print("  we INCREMENTALLY adjust the answer as we move the root around!")
    print()
    print("  • dp1[child] = subtree values (computed once)")
    print("  • parent_contribution = dynamically computed as we reroot")
    print("  • Total time: O(N) - each edge visited twice (once each direction)")
    print()
    print("=" * 80)


if __name__ == "__main__":
    explain_parent_contribution()
